language: node_js
node_js: 13
branches:
  only:
  - source
cache:
  directories:
  - node_modules
before_install:
- npm install -g hexo-cli
- git clone -b master https://github.com/yanandcoffee/hexo-theme-cactus.git themes/cactus
install:
- npm install
script:
- hexo generate
after_success:
- git config --global user.name "yanandcoffee"
- git config --global user.email "mangakjd@gmail.com"
- sed -i'' - sed -i'' "s~git@github.com:yanandcoffee/yanandcoffee.github.io.git~https://${REPO_TOKEN}@github.com/yanandcoffee/yanandcoffee.github.io.git~" _config.yml
- hexo d